### ISSUE TITLE
Bug with new IntelTip option

### ISSUE THREAD

**Issue by aleeperezz16** [evandrocoan/AmxxEditor#17]
Minutes ago the plugin got updated and since then i'm having this scheme bug. Also even though i turn off the new setting: 

> "enable_inteltip_calls"

Neither restarting sublime text takes effect on this.

Img showing the syntax bug:

![imagen](https://user-images.githubusercontent.com/53284952/82111223-f7777880-9719-11ea-832a-750ba9eba854.png)

**Comment by voed** [comment]
Same. Also this intellitip works weird, it does not show up when caret inside function's parenthesis, it shows up only on mouse click, maybe there are some settings for it?

**Comment by evandrocoan** [comment]
I just launched a new update fixing some problems. Now the `enable_inteltip_calls` works correctly to disable things.

@aleeperezz16 What is wrong in the screenshot? To me, everything looks normal.

**Comment by aleeperezz16** [comment]
What i meant was that before the update, non AmxxEditor color schemes didn't show the function parameters as a "function" with that color blue (One Dark Theme). Before that, it looked white like simple text.

**Comment by voed** [comment]
Just suggestion: move links to bottom and make function name and return value single line so it will use less space: 
![image](https://user-images.githubusercontent.com/10352360/82221014-151a2d00-9928-11ea-8ca8-d68858e9d38a.png)
Also highlight current parameter in parameter list(if that possible)

**Comment by evandrocoan** [comment]
@voed, I just implemented support to highlight the active parameter and moved the function return type to the side of the function name but I kept the links on the top because somethings there will be a scrollbar the popup, making hard to see the links:

![image](https://user-images.githubusercontent.com/5332158/82270632-cb433e00-994b-11ea-82d9-c28a29d91b46.png)

**Comment by aleeperezz16** [comment]
The IntelTip now works as it should but i still have the variables for my function parameters shown as a function (with the same color). However this happens only on non predefined themes of AmxxEditor. If it's hard to solve i will just use atomic-pawn theme instead...

**Comment by evandrocoan** [comment]
> the variables for my function parameters shown as a function (with the same color)

This happens because I extended the scope of the function to include the function parameters. This is easily fixed, but you will have to edit the color scheme you are using. What are the color schemes you are having trouble with?

**Comment by aleeperezz16** [comment]
I'm using One Dark Theme so it's not an official AmxxEditor theme. Otherwise i also discovered that the official theme white-pawn has the same problem.

**Comment by evandrocoan** [comment]
I just fixed the problem with white-pawn theme. You can see here https://github.com/evandrocoan/AmxxEditor/commit/97471bc28922b57a6186eb699877880b7f5dcfc8 the changes which need to be done. Basically, we just have to exclude `-support.function.call.paren` from the `support.function` colors.

**Comment by aleeperezz16** [comment]
Well, i could change it:
![imagen](https://user-images.githubusercontent.com/53284952/82284535-9ba62d00-996f-11ea-8b45-af01f6aba280.png)

Unfortunately, functions called inside a function aren't recognized as functions. Anything else i should touch or add on the tmTheme file to make it work?

**Comment by evandrocoan** [comment]
I just released an updating fixing it. You also do not need to edit your `tmTheme` files anymore.

**Comment by aleeperezz16** [comment]
I've installed AmxxPawn plugin and that got fixed. On the other hand, i don't know why this syntax isn't compatible with the other AmxxEditor syntaxes. Also is not full supported by external syntaxes.
Here's a pic:
![imagen](https://user-images.githubusercontent.com/53284952/82358892-88ca4180-99dd-11ea-8b05-69b2da2d089d.png)

Enum tagging changed it's colors and inside function parameters got fixed.
Here's another pic of some special words not correctly highlighting or also not getting highlighted:
![imagen](https://user-images.githubusercontent.com/53284952/82359095-d34bbe00-99dd-11ea-8fb1-83c2bb611073.png)
![imagen](https://user-images.githubusercontent.com/53284952/82359112-dba3f900-99dd-11ea-8f38-2822f4818157.png)
![imagen](https://user-images.githubusercontent.com/53284952/82359154-e6f72480-99dd-11ea-9fb0-8b571b8fde25.png)

**Comment by evandrocoan** [comment]
What is the problem with the pictures? Remember I do not know these color schemes as I use only this https://github.com/evandrocoan/NotepadPlusPlusColorScheme

**Comment by aleeperezz16** [comment]
This one is atomic-pawn with AmxxPawn.sublime-syntax:
![imagen](https://user-images.githubusercontent.com/53284952/82363814-bcf53080-99e4-11ea-856e-250fa2a806fa.png)
This one is atomic-pawn with AmxxEditorPawn.sublime-synxtax:
![imagen](https://user-images.githubusercontent.com/53284952/82363859-ce3e3d00-99e4-11ea-9837-8788658f7f45.png)
What i mean it's that i think you should also update AmxxEditorPawn to work with the new features. Or add to AmxxPawn yo make all syntax work as they should
